re-introduce AlertNotification
Since certain SMPP gateways (osmocom/OpenBSC) will send
an AlertNotification, this would result in the following exception:

Traceback (most recent call last):
  File "test.py", line 43, in <module>
    client.listen()
  File "/home/user/python-smpplib/smpplib/client.py", line 275, in listen
    p = self.read_pdu()
  File "/home/user/python-smpplib/smpplib/client.py", line 218, in read_pdu
    p = smpp.parse_pdu(raw_pdu, client=self)
  File "/home/user/python-smpplib/smpplib/smpp.py", line 45, in parse_pdu
    new_pdu = make_pdu(command, **kwargs)
  File "/home/user/python-smpplib/smpplib/smpp.py", line 32, in make_pdu
    f = command.factory(command_name, **kwargs)
  File "/home/user/python-smpplib/smpplib/command.py", line 61, in factory
    'Command "%s" is not supported' % command_name)
smpplib.exceptions.UnknownCommandError: Command "alert_notification" is not supported